<?php
/*
|--------------------------------------------------------------------------
| Report, generated by maps
|--------------------------------------------------------------------------
| @Created By 	: Elos Ananto
| @Created Date : 01-01-2017
| @Edit By 		: Elos Ananto
| @Edit Date 	: 18-04-2017
| @Reason			: Ajax Call for tracking live
|--------------------------------------------------------------------------
*/
defined('BASEPATH') OR exit('No direct script access allowed');

class Lp_map extends MY_Controller {

	public function __construct(){
			parent::__construct();
			// $this->login();
			$this->load->model('lap_model', '_lap');
	}

	public function index()
	{
			$data["data"] = $this->_lap->data_kejadian_live('1')->result();
			$data['team'] = $this->_lap->sql_data_live()->result();
			// die(print_r($data['team']));
			$this->load->view("v_peta_live", $data);

	}

	function bunch_array(){
		// $data[] = array();
		$kejadian = $this->_lap->data_kejadian_live('1')->result();
		$data_sales = $this->_lap->sql_data_live()->result();
		die(print_r($data_sales));
		$data = $kejadian + $data_sales;
		die(print_r($data));
		return $data;

	}



}
